In [1]:
import numpy as np

In [ ]:
float, int
8-bit (1-byte)
16-bit (2-byte)
64-bit (4-byte)
signed or unsigned?
little-endian, big-endian?

In [ ]:
buffer = b"\x01\x32"
bytes = np.frombuffer(buffer, dtype=np.float16)

array([0.1876], dtype=float16)

In [13]:
f = open('data.dat', 'wb')
f.write(np.array([2, 3, 4], dtype=np.uint8).tobytes())
f.close()

In [15]:
np.save("data.npy", np.array([2, 3, 4], dtype=np.uint8))

In [16]:
np.load("data.npy")

array([2, 3, 4], dtype=uint8)

In [ ]:
np.savez("data2.npz", t=np.linspace(0, 2, 5), volts=np.sin(np.arange(5)))

In [20]:
f = np.load("data2.npz")
f['volts']

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
np.savez_compressed()

In [ ]:
np.memmap()